package cli

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/orjanda-framework/orjanda"
	"github.com/orjanda-framework/orjanda/config"
	"github.com/orjanda-framework/orjanda/dal"
	core "github.com/orjanda-framework/orjanda/orjanda-core"
	"github.com/orjanda-framework/orjanda/schema"
)

// Main runs the orjanda CLI. When configure is non-nil the process is an
// Application binary (generated by `orjanda init`): configure registers the
// Application's Documents against the freshly-created site, so every command
// sees the app's own schema. When configure is nil the process is the
// standalone framework CLI (cmd/orjanda): commands inside an Application
// directory delegate to `go run . <cmd>` so user Documents are compiled
// in-process, and outside one they operate on a core-only site.
//
// See TAD §16 / PRD §21. The configure callback is the TAD §7.1 "registered in
// main.go" composition-root hook surfaced to the CLI.
func Main(configure func(*orjanda.Site) error) {
	root := NewRootCmd(configure)

	args := os.Args[1:]
	if len(args) == 0 && configure != nil {
		// An Application binary run bare defaults to dev serving.
		args = []string{"serve"}
	}
	root.SetArgs(args)

	if err := root.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, "orjanda:", err)
		os.Exit(1)
	}
}

// siteBuilder constructs sites for every command, optionally appending the
// Application's Documents (configure) before compilation.
type siteBuilder struct {
	configure func(*orjanda.Site) error
}

func newSiteBuilder(configure func(*orjanda.Site) error) siteBuilder {
	return siteBuilder{configure: configure}
}

// newSite creates an uncompiled site. The Documents registered by configure
// (or by the core-only default) are compiled by the caller via site.Compile().
func (b siteBuilder) newSite(cfg config.Config) (*orjanda.Site, error) {
	site, err := orjanda.NewSite(cfg)
	if err != nil {
		return nil, err
	}

	// Core User hooks (bcrypt password hashing, TAD §4.1) apply to every site
	// the CLI builds, app binary or core-only, before configure runs.
	core.RegisterUserHooks(site.EventBus)

	if b.configure != nil {
		if err := b.configure(site); err != nil {
			return nil, err
		}
		return site, nil
	}

	site.Install(core.App)
	reg := site.Registry
	for _, d := range []schema.Document{&core.User{}, &core.Role{}, &core.RolePermission{}} {
		if err := reg.Register("core", d); err != nil {
			return nil, err
		}
	}
	return site, nil
}

// loadSite loads the config file ("" for defaults + env), builds the site, and
// compiles the Registry. Compile errors are returned to the caller; serve is
// the only command that downgrades them to a warning (TAD §16).
func (b siteBuilder) loadSite(cfgFile string) (*orjanda.Site, *config.Config, error) {
	cfg, _, err := config.Load(cfgFile)
	if err != nil {
		return nil, nil, err
	}
	site, err := b.newSite(*cfg)
	if err != nil {
		return nil, nil, err
	}
	if err := site.Compile(); err != nil {
		return nil, nil, err
	}
	return site, cfg, nil
}

// delegateToApp runs `go run . <cmd>` in the current directory when it is an
// Application module and this process is the standalone CLI (configure == nil).
// Returns true when delegation happened, in which case the command's own
// in-process logic must not run.
func (b siteBuilder) delegateToApp(ctx context.Context, cmd string, args ...string) (bool, error) {
	if b.configure != nil {
		return false, nil
	}
	if !isOrjandaAppDir(".") {
		return false, nil
	}

	goArgs := append([]string{"run", "."}, append([]string{cmd}, args...)...)
	if err := ensureAppTidy(ctx); err != nil {
		return true, err
	}
	c := exec.CommandContext(ctx, "go", goArgs...)
	c.Stdin = os.Stdin
	c.Stdout = os.Stdout
	c.Stderr = os.Stderr
	if err := c.Run(); err != nil {
		return true, fmt.Errorf("running app in %q failed: %w", ".", err)
	}
	return true, nil
}

// ensureAppTidy resolves the app's dependency graph on first run. Without a
// go.sum the delegated `go run .` fails with "missing go.sum entry"; one tidy
// before the first command makes subsequent runs go straight to `go run`.
func ensureAppTidy(ctx context.Context) error {
	if _, err := os.Stat("go.sum"); err == nil {
		return nil
	}
	fmt.Fprintln(os.Stderr, "orjanda: resolving app module dependencies (go mod tidy)...")
	c := exec.CommandContext(ctx, "go", "mod", "tidy")
	c.Stdin = os.Stdin
	c.Stdout = os.Stdout
	c.Stderr = os.Stderr
	return c.Run()
}

// isOrjandaAppDir reports whether dir contains an Application module: a go.mod
// plus a main.go entry point (the shape produced by `orjanda init`, TAD §16).
func isOrjandaAppDir(dir string) bool {
	goMod := filepath.Join(dir, "go.mod")
	if _, err := os.Stat(goMod); err != nil {
		return false
	}
	mainGo := filepath.Join(dir, "main.go")
	if _, err := os.Stat(mainGo); err != nil {
		return false
	}
	return true
}

// tableCreater is a dal.Database that can also create and register its tables.
// Both concrete dialects implement it; schema management in serve/chat goes
// through this (TAD §16 development), while production migrations go through
// the dal.Migrator.
type tableCreater interface {
	dal.Database
	CreateTables(docs []*schema.CompiledDoc) error
	RegisterDocs(docs []*schema.CompiledDoc)
}

// migratorSource exposes the raw connection and Dialect needed to build a
// dal.Migrator from a dal.Database. Both concrete dialect DBs implement it.
type migratorSource interface {
	Dialect() dal.Dialect
	Underlying() *sql.DB
}
